version: "3"
services:
  cleans:
    build: .
    command: ./cleans
    ports:
      - "1323:1323"
    depends_on:
      - dbs
  dbs:
    restart: always
    image: postgres:13.3-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres

